### ISSUE TITLE
Detect buf.build's buf.yaml for auto configuration of proto roots

### ISSUE THREAD

**Issue by nvx** [devkanro/intellij-protobuf-plugin#74]
When using buf.build to build protobufs a file called `buf.yaml` will exist at the root of the proto directory.

Detecting this file to automatically use these directories as proto roots would be super handy. An option could be added to disable this behaviour if some people found it undesirable for whatever reason.

**Comment by neoeinstein** [comment]
In addition, detecting those `buf.yaml` files and `buf.lock` files. The `buf.lock` files can be interpreted to find roots for dependencies. Here's an example `buf.lock` file.

```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: envoyproxy
    repository: protoc-gen-validate
    commit: dc09a417d27241f7b069feae2cd74a0e
```

On my MacOS machine, this correlates to needing to create a protobuf root at `~/.cache/buf/v1/module/data/buf.build/envoyproxy/protoc-gen-validate/dc09a417d27241f7b069feae2cd74a0e`.
